[tools]
darklua = "seaofvoices/darklua@0.14.1"
rojo = "rojo-rbx/rojo@7.4.4"
lune = "lune-org/lune@0.8.9"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
wally = "UpliftGames/wally@0.3.2"
blink = "1Axen/Blink@0.15.1"
