[dependencies]
signal = "ffrostfall/luausignal@0.4.0"
vide = "alicesaidhi/vide@0.3.1-lite.649"

[dev-dependencies]
ui-labs = "pepeeltoro41/ui-labs@2.3.0"

[package]
name = "ffrostfall/rline"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.0.0-a"
