[dependencies]
signal = "ffrostfall/luausignal@0.4.0"
vide = "alicesaidhi/vide@0.3.1-lite.649"

[dev-dependencies]
ui-labs = "pepeeltoro41/ui-labs@2.3.0"

[package]
exclude = [
	".vscode",
	"rokit.toml",
	"stylua.toml",
	"test-build.project.json",
	"test-source.project.json",
	"selene.toml",
	"selene_definitions.yml",
	"dev-darklua.json",
	"build-darklua.json",
	"build-sourcemap.json",
	"sourcemap.json",
	"build",
	"src",
	"stories",
	"build-sourcemap.project.json",
	"external",
	"lune",
	"tests",
	"vendor",
	".luaurc",
]

name = "ffrostfall/rline"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.0.0-e"
license = "MIT"
include = ["dist"]
